# Appendix C: Preferences

## FREEAPS X
* Glucose Units
* Remote control
* Recommended Insulin Fraction
* Skip Bolus screen after carbs

## OPENAPS MAIN SETTINGS
* Insulin curve
* Max IOB
* Max COB
* Max Daily Safety Multiplier
* Current Basal Safety Multiplier
* Autosens Max
* Autosens Min

## DYNAMIC SETTINGS
* Enable Dynamic ISF
* Enable Dynamic CR
* Adjustment Factor
* Use Logarithmic Formula
* Weighted Average of TDD. Weight of past 24 hours:
* Adjust Basal

## OPEN APS SMB SETTINGS
* Enable SMB Always
* Max Delta-BG Threshold SMB
* Enable SMB with COB
* Enable SMB With Temptarget
* Enable SMB After Carbs
* Allow SMB With High Temptarget
* Enable UAM
* Max SMB Basal Minutes
* SMB DeliveryRatio
* SMB Interval
* Bolus Increment

## OPENAPS TARGETS SETTINGS
* High Temptarget Raises Sensitivity
* Low Temptarget Lowers Sensitivity
* Sensitivity Raises Target
* Sensitivity Lowers Target
* Advanced Target Adjustments
* Exercise Mode
* Half Basal Exercise Target
* Wide BG Target Range

## OPENAPS OTHER SETTINGS
* Rewind Resets Autosens
* Use Custom Peak Time
* Insulin Peak Time
* Skip Neutral Temps
* Unsuspecting If No Temp
* Suspend Zeros IOB
* Bolus Snooze DIA Divisor
* Min 5m Carbimpact
* Autotune ISF Autotune Faction
* Remaining Carbs Faction
* Noisy CGM Target Multiplier

## USE AUTO ISF
* Enable AutoISF

## AUTOISF SETTINGS
FORGET ABOUT THESE IF AUTO ISF ISS TOGGLED OFF
* Enable Floating Carbs
* Enable AutoISF with COB
* Enable BG acceleration in AutoISF 2.2
* AutoISF HourlyMaxChange
* AutoISF Max
* SMB Max RangeExtension
* SMB DeliveryRatio BG Range
* SMB DeliveryRatio BG Minimum
* SMB DeliveryRatio BG Maximum
* ISF weight while BG accelerates
* ISF weight while BG decelerates
* AutoISF Min
* ISF Weight for higher BGs
* ISF weight for lower BGs
* ISF weight for higher BG deltas
* Enable always postprandial ISF adaption
* ISF weight for postprandial BG rise
* Duration ISF postprandial adaption

